set_property SRC_FILE_INFO {cfile:L:/HAWCloud/SSPSynthesize/audio_synthesize/audio_synthesize.srcs/constrs_1/imports/ConstraintsFilesXDC/Modsys_Artix7_AUDIO_Conn_3.xdc rfile:../../../audio_synthesize.srcs/constrs_1/imports/ConstraintsFilesXDC/Modsys_Artix7_AUDIO_Conn_3.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:L:/HAWCloud/SSPSynthesize/audio_synthesize/audio_synthesize.srcs/constrs_1/imports/ConstraintsFilesXDC/Modsys_Artix7_Main_System.xdc rfile:../../../audio_synthesize.srcs/constrs_1/imports/ConstraintsFilesXDC/Modsys_Artix7_Main_System.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A11  [get_ports            {DIN}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K15  [get_ports           {DOUT}]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C12 [get_ports          {SYSCLK}]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D14  [get_ports            {BCK}]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B14 [get_ports             {LRC}]
set_property src_info {type:XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N5 [get_ports              {CLK}]
set_property src_info {type:XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P5 [get_ports          {SRESETN}]
